# Generated by Django 5.0.7 on 2025-05-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
