# Generated by Django 5.0.7 on 2025-05-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertag',
            options={'ordering': ['position']},
        ),
    ]
