services:
  py:
    build: docker/py/
    container_name: ${PY_CNAME}
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./:/hiring-platform/
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: ${DB_CNAME}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - hiring-platform-volume:/var/lib/postgresql/data

#  frontend:
#    image: node:20-alpine
#    container_name: frontend
#    ports:
#      - 3000:3000
#    volumes:
#      - ./:/app
#    working_dir: /app
#    command: npm start
#    environment:
#      - CHOKIDAR_USEPOLLING=true

volumes:
  hiring-platform-volume:
