# Generated by Django 5.0.7 on 2025-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='application_created',
            field=models.BooleanField(default=False),
        ),
    ]
