# Generated by Django 5.0.7 on 2025-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_templates', '0002_answer_application_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtemplate',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
