# Generated by Django 5.0.7 on 2025-06-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_templates', '0003_applicationtemplate_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='custom_requirements',
            field=models.JSONField(default=dict),
        ),
    ]
