# Generated by Django 5.0.7 on 2025-06-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies_templates', '0004_question_custom_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
