# Generated by Django 5.0.7 on 2025-06-07 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taggroup',
            name='name',
        ),
        migrations.CreateModel(
            name='TagGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian')], max_length=10)),
                ('tag_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tags.taggroup')),
            ],
            options={
                'db_table': 'tags_groups_translations',
            },
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian')], max_length=10)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tags.tag')),
            ],
            options={
                'db_table': 'tags_translations',
            },
        ),
    ]
