# Generated by Django 5.0.7 on 2025-06-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_remove_tag_name_remove_taggroup_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taggrouptranslation',
            unique_together={('tag_group', 'language_code')},
        ),
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together={('tag', 'language_code')},
        ),
    ]
