# Generated by Django 5.0.7 on 2025-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_city_country'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='cities',
            field=models.ManyToManyField(related_name='vacancies', to='dict.city'),
        ),
    ]
