# Generated by Django 5.0.7 on 2025-05-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_application_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationanswer',
            options={'ordering': ['id']},
        ),
    ]
