# Generated by Django 5.0.7 on 2025-06-06 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_alter_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian')], max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dict.city')),
            ],
            options={
                'db_table': 'dict_cities_translations',
                'unique_together': {('city', 'language_code')},
            },
        ),
    ]
