# Generated by Django 5.0.7 on 2025-06-06 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_remove_city_name_city_population_citytranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('uk', 'Ukrainian')], max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dict.country')),
            ],
            options={
                'db_table': 'dict_countries_translations',
            },
        ),
    ]
